language: node_js
sudo: true
dist: trusty

node_js:
  - '6.9.1'

branches:
  only:
  - develop

addons:
  sauce_connect: true

before_script:
  - echo $TRAVIS_BRANCH
  - git fetch --unshallow
  - npm install angular-cli@1.0.0-beta.19-3 typescript@2.0.6
  - ng build
  - echo -e 'machine api.heroku.com\n  login josdavis@microsoft.com\n  password '$HEROKU_AUTH'\nmachine git.heroku.com\n  login josdavis@microsoft.com\n  password '$HEROKU_AUTH >> ~/.netrc
  - git remote add heroku https://git.heroku.com/multipli-test.git
  - git branch heroku
  - git checkout heroku
  - git add -f ./dist
  - git commit -am 'adding dist'
  - git push -f heroku heroku:master

script:
  - npm run e2e protractor.sauce.conf.js

after_script:
  - git branch $TRAVIS_BRANCH
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./node_modules/.bin/coveralls < ./coverage/coverage.lcov; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./node_modules/.bin/codecov -f ./coverage/coverage.lcov; fi